### ISSUE TITLE
Auth: `populateConfig` for CLI is missing `object_id` since CLI v2.37.0

### ISSUE THREAD

**Issue by magodo** [hashicorp/go-azure-helpers#118]
Since v2.37.0, CLI migrated the underlying API for `az ad` to using MS graph: https://github.com/Azure/azure-cli/pull/22432. This causes different format for the output of `az ad signed-in-user show -o=json`.

Related issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/16982

**Comment by PeterBrymer** [comment]
It´s stands in the release notes that´s an expected outcome: https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration
