### ISSUE TITLE
Please upgrade Azure SDK to v30 and go-autorest to 11.7

### ISSUE THREAD

**Issue by maxbog** [hashicorp/go-azure-helpers#29]
Hi,

I have a problem authenticating the azurerm backend with a local Azure CLI config. This is basically not supported in go-autorest v10.15.4. 

Support for this was added in v 11.2.4: https://github.com/draychev/go-autorest/commit/572ba1dd7e638bc5e62929f7576c5730f37928ba

Also, the azurerm provider switched recently to v30 of azure sdk and base on this comment: https://github.com/hashicorp/terraform/pull/18968#issuecomment-440744060 the versions should be kept in sync.

I can help with the upgrades if needed.

**Comment by jbpaux** [comment]
@katbyte or @tombuildsstuff what do you think ? :)

**Comment by katbyte** [comment]
Hi @maxbog,

opened #31 that should hopefully resolve this 🙂
