### ISSUE TITLE
Improving the error message used when a SP fails to obtain the authorization token

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/go-azure-helpers#48]
This is the error currently being returned which isn't clear:

```
Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}
```

In order to make this more useful we should wrap this error message and explain the permissions needed.

Reference: https://github.com/terraform-providers/terraform-provider-azurerm/issues/5780

**Comment by mdtusz** [comment]
Is there a known work around for this? Hashicorp locked the linked issue and it's still extremely unclear which permissions the SP requires - even assigning the owner role to the SP for the subscription seems to not work.

**Comment by gaya3chandran1** [comment]
Is there any solution to overcome the problem and proceed with terraform plan?

**Comment by tombuildsstuff** [comment]
This should be resolved now that authentication has been migrated to `hashicorp/go-azure-sdk`, so I'm going to close this one out - @manicminer has been working on improving the logging for authentication specifically, which'll aid with diagnosis too.
